base: &base
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password:
  encoding: utf8
  pool: 10

development:
  <<: *base
  database: blog_app

test:
  <<: *base
  database: blog_app_test

production:
  <<: *base
  database: blog_app
